name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pipenv
        run: pipx install pipenv
      - name: Set up pipenv
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          cache: "pipenv"
      - run: pipenv install
      - name: Test with pytest
        run: pipenv run pytest -v -s